FROM python:3.11.10-alpine3.20

WORKDIR /app

COPY searchengine/ ./searchengine
COPY config/ ./config 

COPY requirements.txt ./
RUN pip install -r requirements.txt  --no-cache-dir 

EXPOSE 8619
CMD [ "python","searchengine/main.py" ]
