FROM ubuntu:22.04

WORKDIR /app

COPY . ./
RUN apt update -y && \
    apt upgrade -y && \
    apt install python3 python3-pip python3-xapian libxapian-dev git -y --no-install-recommends && \
    apt clean -y && \
    pip install -r requirements.txt  --no-cache-dir

RUN git config --global user.name "Bikash" && \
    git config --global user.email "bikashprakashdash@gmail.com"

EXPOSE 8000
CMD [ "python3","embeddedsearch/main.py" ]
